name: classicube
base: core24
summary: Custom Minecraft Classic / ClassiCube client
adopt-info: classicube
description: |
  ClassiCube is a custom Minecraft Classic compatible client written in C
  that works on Windows, macOS, Linux, iOS, Android, FreeBSD, NetBSD, OpenBSD, 
  Solaris, Haiku, IRIX, 3DS (unfinished), PSP (unfinished), and in a web browser.
  It is not affiliated with (or supported by) Mojang AB, Minecraft, or Microsoft 
  in any way.

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
  armhf:


parts:
  libs:
    plugin: nil
    stage-packages:
      - libspeechd2
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
    prime:
      - usr/lib/*/libspeech*
      - usr/lib/*/dri
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/share/vulkan
      - usr/bin/vk*
  launcher:
    plugin: dump
    source: snap/local
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2t64
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libasound*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdnsfile*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libFLAC*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpulse*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamplerate*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libspeex*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvorbis*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
  classicube:
    plugin: make
    after: [alsa-mixin]
    source: https://github.com/ClassiCube/ClassiCube.git
    override-pull: |
      #set -x
      craftctl default
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $CRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      craftctl set version="$(git describe --tags)"
    override-build: |
      #set -x
      make RELEASE=1
      cp credits.txt license.txt ClassiCube $CRAFT_PART_INSTALL
    build-packages:
      - libx11-dev
      - libxi-dev
      - libgl-dev
      - libasound2-dev
    stage-packages:
      - libopenal1
      - libasound2t64
      - libx11-6
      - libxi6
      - libgl1
      - libxcb1
      - libxext6
      - libglvnd0
      - libglx0
      - libxau6
      - libxdmcp6
      - libbsd0
      - libmd0
      - libcurl4t64
  cleanup:
    after: [ classicube ]
    plugin: nil
    build-snaps:  [core24]
    override-prime: |
      set -eux
      for snap in "core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      cd /snap/gnome-46-2404/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  classicube:
    extensions: [gnome]
    command-chain: ["snap/command-chain/alsa-launch"]
    environment:
      ALWAYS_USE_PULSEAUDIO: '1'
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      VK_ICD_FILENAMES: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json
    command: bin/launcher
    plugs:
      - joystick
      - x11
      - opengl
      - audio-playback
      - alsa
      - network
      - network-bind
      - home
      - removable-media
      - wayland


